// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0OkSfB7ETKYJQFvtb0fbl2XB0T-aLa0',
    appId: '1:367139089445:web:9ac1178a62cac4c93f63cc',
    messagingSenderId: '367139089445',
    projectId: 'ichat-f7b0b',
    authDomain: 'ichat-f7b0b.firebaseapp.com',
    storageBucket: 'ichat-f7b0b.appspot.com',
    measurementId: 'G-SFBM31F3QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2iO-w5qU3stpgVV2DocHFKtpMsCIddqc',
    appId: '1:367139089445:android:e96b4bdae5856fd73f63cc',
    messagingSenderId: '367139089445',
    projectId: 'ichat-f7b0b',
    storageBucket: 'ichat-f7b0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87ZCmeU3JccTE-D-OVj9mdq-EfN9icjk',
    appId: '1:367139089445:ios:640e2870d832fcbf3f63cc',
    messagingSenderId: '367139089445',
    projectId: 'ichat-f7b0b',
    storageBucket: 'ichat-f7b0b.appspot.com',
    androidClientId: '367139089445-ls0th7icrrisj6f8epqrbf8a7uj4bfpo.apps.googleusercontent.com',
    iosClientId: '367139089445-70mkiviuahkv1t2ovevtu4h74493p69k.apps.googleusercontent.com',
    iosBundleId: 'com.zee.devs.iChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87ZCmeU3JccTE-D-OVj9mdq-EfN9icjk',
    appId: '1:367139089445:ios:5a8d0fa4888d02603f63cc',
    messagingSenderId: '367139089445',
    projectId: 'ichat-f7b0b',
    storageBucket: 'ichat-f7b0b.appspot.com',
    androidClientId: '367139089445-ls0th7icrrisj6f8epqrbf8a7uj4bfpo.apps.googleusercontent.com',
    iosClientId: '367139089445-ivivgh8ik1vmlcqn28f5t4kfb8b5jokl.apps.googleusercontent.com',
    iosBundleId: 'com.zee.devs.iChatApp.RunnerTests',
  );
}
